### PR TITLE
Rewrite 3D CHGCAR/LOCPOT reading algo for speed

### PR DESCRIPTION
**Pull request by ajjackson**
Profiling shows that reading the density/locpot files is the slowest part of using Macrodensity so I investigated some ways of speeding it up. `read_vasp_density` has been replaced with an entirely new implementation. This one is not robust against randomly-placed newlines; hopefully that wasn't very important. Everything is now done in a single pass over the file, as lazily as possible.

The previous algorithm has been retained as "read_vasp_density_legacy" and a streamlined version of that algorithm has been retained as "read_vasp_density_classic".

Sadly the line number updates had to go as the `if` statements were actually quite expensive. I'm in favour of keeping the iconic BOOM for now though!

Some other things that were tried:
- The numpy file readers were surprisingly terrible.
- numpy's float parser is faster than converting to float first
- Replacing .split() with column slicing didn't really help.
- The pandas file-reader is incredibly fast, but it's a weird dependency for the project and a bit cumbersome in this application.

For the Slab tutorial file, my typical numbers are > 20s for "legacy", 10s for "classic" and 8s for the new loader.

### CODE REVIEW

**Comment by ajjackson** [comment]
For fun I've added the Pandas-based version as `read_vasp_density_pandas`. On my macbook air (SSD, 2.2 GHz i7) the lazy version is consistently hitting 7-8s while the Pandas-based one is consistently hitting < 5 seconds. We could make it an optional dependency and use it when available?

What is a bit strange is that the average potential is slightly different, although the individual values I've inspected seem fine. The average is a number of the order 1e-15, so this is probably due to a difference in stored numerical precision?

**Comment by ajjackson** [comment]
Ok, latest version uses Pandas when available and includes a test which breaks Pandas and checks the fallback version.

**Comment by ajjackson** [comment]
I'm baffled by the Travis CI failure here. I don't get this error when I run the tests, and it seems to be caused by a missing "quiet" option in the `read_vasp_density` function... which is clearly [right here](https://github.com/WMD-group/MacroDensity/blob/8fac97e8c6cfacd6a0350ef4425f4c9fd105e3c4/macrodensity/density_tools.py#L265) in the source code.

**Comment by ajjackson** [comment]
Tried:

- uninstall macrodensity
- clone a clean copy of this branch to a new folder
- reinstall from the new folder
- run tests
with no problem at all.

Tried re-running Travis CI build, getting the same error.

**Comment by ajjackson** [comment]
Fixed! The problem is that the Travis setup was installing from the master branch instead of the local directory. I've also added Python 3 testing and tweaked the test command as we aren't actually using pytest

**Comment by ajjackson** [comment]
Ok, the only remaining build issue is a codeclimate complaint about the legacy code using an extended if/elif arrangement ¯\\\_(ツ)\_/¯

I think this is good to go!

**Comment by keeeto** [comment]
I don't understand why Travis is now failing to find the CHGCAR.test that is required for the unit tests. The unit tests all pass for me and I would like to approve this PR. But I need to sort out the build fail before I do.

**Comment by ajjackson** [comment]
**bump** is this ok to merge now?

**Comment by keeeto** [comment]
Thanks @ajjackson

**Pull request merged**
