### PR TITLE
Add ability to read spin polarised PARCHG

### PR DESCRIPTION
**Pull request by keeeto**
This PR adds the ability to read a `PARCHG` file from a spin polarised VASP calculation. The function now takes an additional keyword `spin` and in the case of a spin polarised calculation, `spin=True`, returns the alpha and beta spin densities as two arrays.

### CODE REVIEW

**Review by ajjackson — APPROVED** [review]
This looks fine to me and it comes with a test! I'm just taking a look at the codeclimate report to see if there are any sensible tweaks suggested.

I haven't tested with further sample data, I'm assuming the one you're testing on is representative.

**Comment by ajjackson** [comment]
Nah, the codeclimate suggestions are about refactoring for redundancy between the file importers. Given that they are for different file formats I'm comfortable with the repetition there.

**Comment by ajjackson** [comment]
Shall I hit merge or were you planning to tweak this further?

**Comment by keeeto** [comment]
Good to merge! Thanks @ajjackson !

**Pull request merged**
